=== 19317362/wro4j/wro4j-core/src/main/resources/ro/isdc/wro/wro.xsd
<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.isdc.ro/wro" xmlns="http://www.isdc.ro/wro"
	elementFormDefault="qualified">
	<xsd:element name="groups" type="Groups" />
	<xsd:complexType name="Groups">
		<xsd:sequence>
			<xsd:element name="group" type="Group" minOccurs="1"
				maxOccurs="unbounded" />
		</xsd:sequence>
	</xsd:complexType>
	<xsd:attributeGroup name="wroelemgroup">
		<xsd:attribute name="browsers" type="xsd:string" />
		<xsd:attribute name="negated">
			<xsd:simpleType>
				<xsd:restriction base="xsd:string">
					<xsd:pattern value="true|false" />
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
	</xsd:attributeGroup>
	<xsd:complexType name="Group">
		<xsd:choice maxOccurs="unbounded" minOccurs="1">
			<xsd:element name="css">
				<xsd:complexType>
					<xsd:simpleContent>
						<xsd:extension base="xsd:string">
							<xsd:attributeGroup ref="wroelemgroup" />
						</xsd:extension>
					</xsd:simpleContent>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="js">
				<xsd:complexType>
					<xsd:simpleContent>
						<xsd:extension base="xsd:string">
							<xsd:attributeGroup ref="wroelemgroup" />
						</xsd:extension>
					</xsd:simpleContent>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="group-ref">
				<xsd:complexType>
					<xsd:simpleContent>
						<xsd:extension base="xsd:IDREF">
							<xsd:attributeGroup ref="wroelemgroup" />
						</xsd:extension>
					</xsd:simpleContent>
				</xsd:complexType>
			</xsd:element>
		</xsd:choice>
		<xsd:attribute name="name" type="xsd:ID" use="required" />
	</xsd:complexType>
</xsd:schema>

=== 19317362/wro4j/wro4j-examples/src/main/webapp/WEB-INF/wro.xml
<?xml version="1.0" encoding="UTF-8"?>
<groups xmlns="http://www.isdc.ro/wro"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.isdc.ro/wro wro.xsd">

  <group name="all">
    <group-ref>uniform</group-ref>
    <group-ref>JSGroup</group-ref>
  </group>

  <group name="uniform">
    <!--css>file:c:/temp/fileFromDisk.css</css-->
    <css>/static/css/webapp.css</css>
    <css browsers="ie,opera10">/static/css/css1.css</css>
    <css browsers="chrome">/static/css/css2.css</css>
    <css browsers="ff">/static/css/css${number}.css</css>
    <css>classpath:ro/isdc/wro/resources/classpath.css</css>
    <css>classpath:com/resources/css/classpath.css</css>
  </group>

  <group name="dwr">
    <js>/dwr/engine.js</js>
    <js>/dwr/interface/DWRFacade.js</js>
  </group>

  <group name="JSGroup">
    <js browsers="ie,gecko">/static/js/css-browser-selector.js</js>
    <js>/static/js/jquery.js</js>
    <js>/static/js/jquery.blockUI.js</js>
    <js>/static/js/jquery.selectboxes.js</js>
    <js>/static/js/DOMWindow.js</js>
    <js>/static/js/calendar_stripped.js</js>
    <js>/static/js/base.js</js>
    <js>/static/js/validator-src.js</js>
    <js>/static/js/error-handlers-src.js</js>
    <js>/static/js/stringify.js</js>
    <js>/dwr/engine.js</js>
    <js>/dwr/interface/DWRFacade.js</js>
  </group>

  <group name="jquery">
    <js>/static/js/jquery.js</js>
    <js>/static/js/jquery.livequery.js</js>
    <js>/static/js/jquery-validate.js</js>
    <js>/static/js/jquery-ui-all.js</js>
  </group>

</groups>

=== 19317362/wro4j/wro4j-maven-plugin/src/test/resources/wro.xml
<?xml version="1.0" encoding="UTF-8"?>
<groups xmlns="http://www.isdc.ro/wro"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.isdc.ro/wro wro.xsd">

  <group name="g1">
    <group-ref>g2</group-ref>
    <group-ref>g3</group-ref>
  </group>
  
  <group name="invalidResources">
    <js>classpath:ro/isdc/wro/maven/plugin/js/invalid.js</js>
  </group>
  
  <group name="undef">
    <js>classpath:ro/isdc/wro/maven/plugin/js/undef.js</js>
  </group>
  
  <group name="wildcard">
    <js>classpath:ro/isdc/wro/maven/plugin/js/**</js>
  </group>

  <group name="g2">
    <js>classpath:ro/isdc/wro/maven/plugin/js/1.js</js>
  </group>
  
  <group name="g3">
    <js>classpath:ro/isdc/wro/maven/plugin/js/2.js</js>
  </group>
  
  <group name="g4">
    <js>classpath:ro/isdc/wro/maven/plugin/js/*.js</js>
  </group>
</groups>

=== 19317362/wro4j/wro4j-core/src/test/resources/ro/isdc/wro/http/wro.xml
<?xml version="1.0" encoding="UTF-8"?>
<groups xmlns="http://www.isdc.ro/wro"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.isdc.ro/wro wro.xsd">

  <group name="g1">
    <group-ref>g2</group-ref>
    <group-ref>g3</group-ref>
  </group>

  <group name="g2">
    <css>classpath:ro/isdc/wro/http/1.css</css>
  </group>
  
  <group name="g3">
    <css>classpath:ro/isdc/wro/http/2.css</css>
  </group>
</groups>

=== 19317362/wro4j/wro.xml
<?xml version="1.0" encoding="UTF-8"?>
<groups xmlns="http://www.isdc.ro/wro"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.isdc.ro/wro wro.xsd">

  <group name="all">
  	<js>/asset/js/**.js</js>
    <css>/asset/**.css</css>
    <group-ref>syntaxHighlighter</group-ref>
  </group>
  
  <group name="syntaxHighlighter">
  	<js>/asset/syntaxHighlighter/**.js</js>
    <css>/asset/syntaxHighlighter/styles/shCore.css</css>
    <css>/asset/syntaxHighlighter/styles/shCoreDefault.css</css>
  </group>
</groups>

=== 19317362/wro4j/wro4j-core/src/test/resources/wro.xml
<?xml version="1.0" encoding="UTF-8"?>

<wro:groups xmlns:wro="http://www.isdc.ro/wro"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.isdc.ro/wro ../../main/resources/wro.xsd">

	<group name="g1">
		<js>classpath:1.js</js>
		<css>classpath:1.css</css>
		<group-ref>g2</group-ref>
    <group-ref>dwr</group-ref>
	</group>

	<group name="dwr">
		<js>http://localhost:8080/wfc/dwr/engine.js</js>
		<js>http://localhost:8080/wfc/dwr/interface/DWRFacade.js</js>
	</group>

	<group name="g2">
		<js>classpath:2.js</js>
		<group-ref>g3</group-ref>
		<css>classpath:2.css</css>
	</group>

	<group name="g3">
		<css>classpath:3.css</css>
		<js>classpath:3.js</js>
	</group>

</wro:groups>

=== 19317362/wro4j/wro4j-core/src/test/resources/ro/isdc/wro/model/wro.xml
<?xml version="1.0" encoding="UTF-8"?>
<groups xmlns="http://www.isdc.ro/wro"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.isdc.ro/wro wro.xsd">

  <group name="g1">
    <css>classpath:1.css</css>
  </group>

  <group name="g2">
    <css>/path/to/resource</css>
    <js>/path/to/resource</js>
  </group>
  
  <group name="g3">
    <js>/path/to/resource</js>
    <group-ref>g2</group-ref>
  </group>
</groups>
